#定义一个yaml配置文件
OpenBrowser:         true
DisableLAN:          false
Port:                22545
CheckImageInServer:  false
LogToFile:           false
MaxDepth:            2
MinImageNum:         3
ZipFilenameEncoding: ""
EnableWebpServer: false
WebpConfig: 
　WebpCommand:  "webp-server"
　HOST:         "127.0.0.1"
　PORT:         "3333"
　ImgPath:      ""
　QUALITY:      70
　AllowedTypes: 
    - jpg
    - png
    - jpeg
    - bmp
　ExhaustPath: 　""
EnableFrpcServer: true
FrpConfig: 
  FrpcCommand: "frpc"
  ServerAddr:  "sh.youdomain.net" 
  ServerPort:  7000      
  Token:       "NscevW3Usss"
  FrpType:     "tcp"
  RemotePort:  -1 
  RandomRemotePort: true
ServerHost: ""