#定义一个yaml配置文件
OpenBrowser:         false
DisableLAN:          false
Port:                1234
CheckImageInServer:  true
LogToFile:           false
MaxDepth:            1
MinImageNum:         3
ZipFilenameEncoding: ""
EnableWebpServer: false
WebpConfig: 
　WebpCommand:  "webp-server"
　HOST:         "127.0.0.1"
　PORT:         "3333"
　ImgPath:      ""
　QUALITY:      100
　AllowedTypes: 
    - jpg
    - png
    - jpeg
    - bmp
　ExhaustPath: 　""
EnableFrpcServer: false
FrpConfig: 
  FrpcCommand: "frpc"
  ServerAddr:  "sh.japari-park.net" 
  ServerPort:  7000      
  Token:       "NscevW3U%F"
  FrpType:     "tcp"
  RemotePort:  -1 
ServerHost: ""